DROP DATABASE esbifarma;
CREATE DATABASE esbifarma;
USE esbifarma;

CREATE TABLE tb_provinces(
	id char(2) NOT NULL COMMENT 'ID Provinsi',
	name char(250) NOT NULL COMMENT 'Nama Provinsi'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Provinsi.';

INSERT INTO tb_provinces VALUES
('11', 'ACEH'),
('12', 'SUMATERA UTARA'),
('13', 'SUMATERA BARAT'),
('14', 'RIAU'),
('15', 'JAMBI'),
('16', 'SUMATERA SELATAN'),
('17', 'BENGKULU'),
('18', 'LAMPUNG'),
('19', 'KEPULAUAN BANGKA BELITUNG'),
('21', 'KEPULAUAN RIAU'),
('31', 'DKI JAKARTA'),
('32', 'JAWA BARAT'),
('33', 'JAWA TENGAH'),
('34', 'DI YOGYAKARTA'),
('35', 'JAWA TIMUR'),
('36', 'BANTEN'),
('51', 'BALI'),
('52', 'NUSA TENGGARA BARAT'),
('53', 'NUSA TENGGARA TIMUR'),
('61', 'KALIMANTAN BARAT'),
('62', 'KALIMANTAN TENGAH'),
('63', 'KALIMANTAN SELATAN'),
('64', 'KALIMANTAN TIMUR'),
('65', 'KALIMANTAN UTARA'),
('71', 'SULAWESI UTARA'),
('72', 'SULAWESI TENGAH'),
('73', 'SULAWESI SELATAN'),
('74', 'SULAWESI TENGGARA'),
('75', 'GORONTALO'),
('76', 'SULAWESI BARAT'),
('81', 'MALUKU'),
('82', 'MALUKU UTARA'),
('91', 'PAPUA BARAT'),
('94', 'PAPUA');

CREATE TABLE tb_cities(
	id char(4) NOT NULL COMMENT 'ID Kota atau Kabupaten',
	province_id char(2) NOT NULL COMMENT 'ID Provinsi',
	name char(250) NOT NULL COMMENT 'Nama Kota atau Kabupaten'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Kota atau Kabupaten.';

INSERT INTO `tb_cities` VALUES
('1101', '11', 'KABUPATEN SIMEULUE'),
('1102', '11', 'KABUPATEN ACEH SINGKIL'),
('1103', '11', 'KABUPATEN ACEH SELATAN'),
('1104', '11', 'KABUPATEN ACEH TENGGARA'),
('1105', '11', 'KABUPATEN ACEH TIMUR'),
('1106', '11', 'KABUPATEN ACEH TENGAH'),
('1107', '11', 'KABUPATEN ACEH BARAT'),
('1108', '11', 'KABUPATEN ACEH BESAR'),
('1109', '11', 'KABUPATEN PIDIE'),
('1110', '11', 'KABUPATEN BIREUEN'),
('1111', '11', 'KABUPATEN ACEH UTARA'),
('1112', '11', 'KABUPATEN ACEH BARAT DAYA'),
('1113', '11', 'KABUPATEN GAYO LUES'),
('1114', '11', 'KABUPATEN ACEH TAMIANG'),
('1115', '11', 'KABUPATEN NAGAN RAYA'),
('1116', '11', 'KABUPATEN ACEH JAYA'),
('1117', '11', 'KABUPATEN BENER MERIAH'),
('1118', '11', 'KABUPATEN PIDIE JAYA'),
('1171', '11', 'KOTA BANDA ACEH'),
('1172', '11', 'KOTA SABANG'),
('1173', '11', 'KOTA LANGSA'),
('1174', '11', 'KOTA LHOKSEUMAWE'),
('1175', '11', 'KOTA SUBULUSSALAM'),
('1201', '12', 'KABUPATEN NIAS'),
('1202', '12', 'KABUPATEN MANDAILING NATAL'),
('1203', '12', 'KABUPATEN TAPANULI SELATAN'),
('1204', '12', 'KABUPATEN TAPANULI TENGAH'),
('1205', '12', 'KABUPATEN TAPANULI UTARA'),
('1206', '12', 'KABUPATEN TOBA SAMOSIR'),
('1207', '12', 'KABUPATEN LABUHAN BATU'),
('1208', '12', 'KABUPATEN ASAHAN'),
('1209', '12', 'KABUPATEN SIMALUNGUN'),
('1210', '12', 'KABUPATEN DAIRI'),
('1211', '12', 'KABUPATEN KARO'),
('1212', '12', 'KABUPATEN DELI SERDANG'),
('1213', '12', 'KABUPATEN LANGKAT'),
('1214', '12', 'KABUPATEN NIAS SELATAN'),
('1215', '12', 'KABUPATEN HUMBANG HASUNDUTAN'),
('1216', '12', 'KABUPATEN PAKPAK BHARAT'),
('1217', '12', 'KABUPATEN SAMOSIR'),
('1218', '12', 'KABUPATEN SERDANG BEDAGAI'),
('1219', '12', 'KABUPATEN BATU BARA'),
('1220', '12', 'KABUPATEN PADANG LAWAS UTARA'),
('1221', '12', 'KABUPATEN PADANG LAWAS'),
('1222', '12', 'KABUPATEN LABUHAN BATU SELATAN'),
('1223', '12', 'KABUPATEN LABUHAN BATU UTARA'),
('1224', '12', 'KABUPATEN NIAS UTARA'),
('1225', '12', 'KABUPATEN NIAS BARAT'),
('1271', '12', 'KOTA SIBOLGA'),
('1272', '12', 'KOTA TANJUNG BALAI'),
('1273', '12', 'KOTA PEMATANG SIANTAR'),
('1274', '12', 'KOTA TEBING TINGGI'),
('1275', '12', 'KOTA MEDAN'),
('1276', '12', 'KOTA BINJAI'),
('1277', '12', 'KOTA PADANGSIDIMPUAN'),
('1278', '12', 'KOTA GUNUNGSITOLI'),
('1301', '13', 'KABUPATEN KEPULAUAN MENTAWAI'),
('1302', '13', 'KABUPATEN PESISIR SELATAN'),
('1303', '13', 'KABUPATEN SOLOK'),
('1304', '13', 'KABUPATEN SIJUNJUNG'),
('1305', '13', 'KABUPATEN TANAH DATAR'),
('1306', '13', 'KABUPATEN PADANG PARIAMAN'),
('1307', '13', 'KABUPATEN AGAM'),
('1308', '13', 'KABUPATEN LIMA PULUH KOTA'),
('1309', '13', 'KABUPATEN PASAMAN'),
('1310', '13', 'KABUPATEN SOLOK SELATAN'),
('1311', '13', 'KABUPATEN DHARMASRAYA'),
('1312', '13', 'KABUPATEN PASAMAN BARAT'),
('1371', '13', 'KOTA PADANG'),
('1372', '13', 'KOTA SOLOK'),
('1373', '13', 'KOTA SAWAH LUNTO'),
('1374', '13', 'KOTA PADANG PANJANG'),
('1375', '13', 'KOTA BUKITTINGGI'),
('1376', '13', 'KOTA PAYAKUMBUH'),
('1377', '13', 'KOTA PARIAMAN'),
('1401', '14', 'KABUPATEN KUANTAN SINGINGI'),
('1402', '14', 'KABUPATEN INDRAGIRI HULU'),
('1403', '14', 'KABUPATEN INDRAGIRI HILIR'),
('1404', '14', 'KABUPATEN PELALAWAN'),
('1405', '14', 'KABUPATEN S I A K'),
('1406', '14', 'KABUPATEN KAMPAR'),
('1407', '14', 'KABUPATEN ROKAN HULU'),
('1408', '14', 'KABUPATEN BENGKALIS'),
('1409', '14', 'KABUPATEN ROKAN HILIR'),
('1410', '14', 'KABUPATEN KEPULAUAN MERANTI'),
('1471', '14', 'KOTA PEKANBARU'),
('1473', '14', 'KOTA DUMAI'),
('1501', '15', 'KABUPATEN KERINCI'),
('1502', '15', 'KABUPATEN MERANGIN'),
('1503', '15', 'KABUPATEN SAROLANGUN'),
('1504', '15', 'KABUPATEN BATANG HARI'),
('1505', '15', 'KABUPATEN MUARO JAMBI'),
('1506', '15', 'KABUPATEN TANJUNG JABUNG TIMUR'),
('1507', '15', 'KABUPATEN TANJUNG JABUNG BARAT'),
('1508', '15', 'KABUPATEN TEBO'),
('1509', '15', 'KABUPATEN BUNGO'),
('1571', '15', 'KOTA JAMBI'),
('1572', '15', 'KOTA SUNGAI PENUH'),
('1601', '16', 'KABUPATEN OGAN KOMERING ULU'),
('1602', '16', 'KABUPATEN OGAN KOMERING ILIR'),
('1603', '16', 'KABUPATEN MUARA ENIM'),
('1604', '16', 'KABUPATEN LAHAT'),
('1605', '16', 'KABUPATEN MUSI RAWAS'),
('1606', '16', 'KABUPATEN MUSI BANYUASIN'),
('1607', '16', 'KABUPATEN BANYU ASIN'),
('1608', '16', 'KABUPATEN OGAN KOMERING ULU SELATAN'),
('1609', '16', 'KABUPATEN OGAN KOMERING ULU TIMUR'),
('1610', '16', 'KABUPATEN OGAN ILIR'),
('1611', '16', 'KABUPATEN EMPAT LAWANG'),
('1612', '16', 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'),
('1613', '16', 'KABUPATEN MUSI RAWAS UTARA'),
('1671', '16', 'KOTA PALEMBANG'),
('1672', '16', 'KOTA PRABUMULIH'),
('1673', '16', 'KOTA PAGAR ALAM'),
('1674', '16', 'KOTA LUBUKLINGGAU'),
('1701', '17', 'KABUPATEN BENGKULU SELATAN'),
('1702', '17', 'KABUPATEN REJANG LEBONG'),
('1703', '17', 'KABUPATEN BENGKULU UTARA'),
('1704', '17', 'KABUPATEN KAUR'),
('1705', '17', 'KABUPATEN SELUMA'),
('1706', '17', 'KABUPATEN MUKOMUKO'),
('1707', '17', 'KABUPATEN LEBONG'),
('1708', '17', 'KABUPATEN KEPAHIANG'),
('1709', '17', 'KABUPATEN BENGKULU TENGAH'),
('1771', '17', 'KOTA BENGKULU'),
('1801', '18', 'KABUPATEN LAMPUNG BARAT'),
('1802', '18', 'KABUPATEN TANGGAMUS'),
('1803', '18', 'KABUPATEN LAMPUNG SELATAN'),
('1804', '18', 'KABUPATEN LAMPUNG TIMUR'),
('1805', '18', 'KABUPATEN LAMPUNG TENGAH'),
('1806', '18', 'KABUPATEN LAMPUNG UTARA'),
('1807', '18', 'KABUPATEN WAY KANAN'),
('1808', '18', 'KABUPATEN TULANGBAWANG'),
('1809', '18', 'KABUPATEN PESAWARAN'),
('1810', '18', 'KABUPATEN PRINGSEWU'),
('1811', '18', 'KABUPATEN MESUJI'),
('1812', '18', 'KABUPATEN TULANG BAWANG BARAT'),
('1813', '18', 'KABUPATEN PESISIR BARAT'),
('1871', '18', 'KOTA BANDAR LAMPUNG'),
('1872', '18', 'KOTA METRO'),
('1901', '19', 'KABUPATEN BANGKA'),
('1902', '19', 'KABUPATEN BELITUNG'),
('1903', '19', 'KABUPATEN BANGKA BARAT'),
('1904', '19', 'KABUPATEN BANGKA TENGAH'),
('1905', '19', 'KABUPATEN BANGKA SELATAN'),
('1906', '19', 'KABUPATEN BELITUNG TIMUR'),
('1971', '19', 'KOTA PANGKAL PINANG'),
('2101', '21', 'KABUPATEN KARIMUN'),
('2102', '21', 'KABUPATEN BINTAN'),
('2103', '21', 'KABUPATEN NATUNA'),
('2104', '21', 'KABUPATEN LINGGA'),
('2105', '21', 'KABUPATEN KEPULAUAN ANAMBAS'),
('2171', '21', 'KOTA BATAM'),
('2172', '21', 'KOTA TANJUNG PINANG'),
('3101', '31', 'KABUPATEN KEPULAUAN SERIBU'),
('3171', '31', 'KOTA JAKARTA SELATAN'),
('3172', '31', 'KOTA JAKARTA TIMUR'),
('3173', '31', 'KOTA JAKARTA PUSAT'),
('3174', '31', 'KOTA JAKARTA BARAT'),
('3175', '31', 'KOTA JAKARTA UTARA'),
('3201', '32', 'KABUPATEN BOGOR'),
('3202', '32', 'KABUPATEN SUKABUMI'),
('3203', '32', 'KABUPATEN CIANJUR'),
('3204', '32', 'KABUPATEN BANDUNG'),
('3205', '32', 'KABUPATEN GARUT'),
('3206', '32', 'KABUPATEN TASIKMALAYA'),
('3207', '32', 'KABUPATEN CIAMIS'),
('3208', '32', 'KABUPATEN KUNINGAN'),
('3209', '32', 'KABUPATEN CIREBON'),
('3210', '32', 'KABUPATEN MAJALENGKA'),
('3211', '32', 'KABUPATEN SUMEDANG'),
('3212', '32', 'KABUPATEN INDRAMAYU'),
('3213', '32', 'KABUPATEN SUBANG'),
('3214', '32', 'KABUPATEN PURWAKARTA'),
('3215', '32', 'KABUPATEN KARAWANG'),
('3216', '32', 'KABUPATEN BEKASI'),
('3217', '32', 'KABUPATEN BANDUNG BARAT'),
('3218', '32', 'KABUPATEN PANGANDARAN'),
('3271', '32', 'KOTA BOGOR'),
('3272', '32', 'KOTA SUKABUMI'),
('3273', '32', 'KOTA BANDUNG'),
('3274', '32', 'KOTA CIREBON'),
('3275', '32', 'KOTA BEKASI'),
('3276', '32', 'KOTA DEPOK'),
('3277', '32', 'KOTA CIMAHI'),
('3278', '32', 'KOTA TASIKMALAYA'),
('3279', '32', 'KOTA BANJAR'),
('3301', '33', 'KABUPATEN CILACAP'),
('3302', '33', 'KABUPATEN BANYUMAS'),
('3303', '33', 'KABUPATEN PURBALINGGA'),
('3304', '33', 'KABUPATEN BANJARNEGARA'),
('3305', '33', 'KABUPATEN KEBUMEN'),
('3306', '33', 'KABUPATEN PURWOREJO'),
('3307', '33', 'KABUPATEN WONOSOBO'),
('3308', '33', 'KABUPATEN MAGELANG'),
('3309', '33', 'KABUPATEN BOYOLALI'),
('3310', '33', 'KABUPATEN KLATEN'),
('3311', '33', 'KABUPATEN SUKOHARJO'),
('3312', '33', 'KABUPATEN WONOGIRI'),
('3313', '33', 'KABUPATEN KARANGANYAR'),
('3314', '33', 'KABUPATEN SRAGEN'),
('3315', '33', 'KABUPATEN GROBOGAN'),
('3316', '33', 'KABUPATEN BLORA'),
('3317', '33', 'KABUPATEN REMBANG'),
('3318', '33', 'KABUPATEN PATI'),
('3319', '33', 'KABUPATEN KUDUS'),
('3320', '33', 'KABUPATEN JEPARA'),
('3321', '33', 'KABUPATEN DEMAK'),
('3322', '33', 'KABUPATEN SEMARANG'),
('3323', '33', 'KABUPATEN TEMANGGUNG'),
('3324', '33', 'KABUPATEN KENDAL'),
('3325', '33', 'KABUPATEN BATANG'),
('3326', '33', 'KABUPATEN PEKALONGAN'),
('3327', '33', 'KABUPATEN PEMALANG'),
('3328', '33', 'KABUPATEN TEGAL'),
('3329', '33', 'KABUPATEN BREBES'),
('3371', '33', 'KOTA MAGELANG'),
('3372', '33', 'KOTA SURAKARTA'),
('3373', '33', 'KOTA SALATIGA'),
('3374', '33', 'KOTA SEMARANG'),
('3375', '33', 'KOTA PEKALONGAN'),
('3376', '33', 'KOTA TEGAL'),
('3401', '34', 'KABUPATEN KULON PROGO'),
('3402', '34', 'KABUPATEN BANTUL'),
('3403', '34', 'KABUPATEN GUNUNG KIDUL'),
('3404', '34', 'KABUPATEN SLEMAN'),
('3471', '34', 'KOTA YOGYAKARTA'),
('3501', '35', 'KABUPATEN PACITAN'),
('3502', '35', 'KABUPATEN PONOROGO'),
('3503', '35', 'KABUPATEN TRENGGALEK'),
('3504', '35', 'KABUPATEN TULUNGAGUNG'),
('3505', '35', 'KABUPATEN BLITAR'),
('3506', '35', 'KABUPATEN KEDIRI'),
('3507', '35', 'KABUPATEN MALANG'),
('3508', '35', 'KABUPATEN LUMAJANG'),
('3509', '35', 'KABUPATEN JEMBER'),
('3510', '35', 'KABUPATEN BANYUWANGI'),
('3511', '35', 'KABUPATEN BONDOWOSO'),
('3512', '35', 'KABUPATEN SITUBONDO'),
('3513', '35', 'KABUPATEN PROBOLINGGO'),
('3514', '35', 'KABUPATEN PASURUAN'),
('3515', '35', 'KABUPATEN SIDOARJO'),
('3516', '35', 'KABUPATEN MOJOKERTO'),
('3517', '35', 'KABUPATEN JOMBANG'),
('3518', '35', 'KABUPATEN NGANJUK'),
('3519', '35', 'KABUPATEN MADIUN'),
('3520', '35', 'KABUPATEN MAGETAN'),
('3521', '35', 'KABUPATEN NGAWI'),
('3522', '35', 'KABUPATEN BOJONEGORO'),
('3523', '35', 'KABUPATEN TUBAN'),
('3524', '35', 'KABUPATEN LAMONGAN'),
('3525', '35', 'KABUPATEN GRESIK'),
('3526', '35', 'KABUPATEN BANGKALAN'),
('3527', '35', 'KABUPATEN SAMPANG'),
('3528', '35', 'KABUPATEN PAMEKASAN'),
('3529', '35', 'KABUPATEN SUMENEP'),
('3571', '35', 'KOTA KEDIRI'),
('3572', '35', 'KOTA BLITAR'),
('3573', '35', 'KOTA MALANG'),
('3574', '35', 'KOTA PROBOLINGGO'),
('3575', '35', 'KOTA PASURUAN'),
('3576', '35', 'KOTA MOJOKERTO'),
('3577', '35', 'KOTA MADIUN'),
('3578', '35', 'KOTA SURABAYA'),
('3579', '35', 'KOTA BATU'),
('3601', '36', 'KABUPATEN PANDEGLANG'),
('3602', '36', 'KABUPATEN LEBAK'),
('3603', '36', 'KABUPATEN TANGERANG'),
('3604', '36', 'KABUPATEN SERANG'),
('3671', '36', 'KOTA TANGERANG'),
('3672', '36', 'KOTA CILEGON'),
('3673', '36', 'KOTA SERANG'),
('3674', '36', 'KOTA TANGERANG SELATAN'),
('5101', '51', 'KABUPATEN JEMBRANA'),
('5102', '51', 'KABUPATEN TABANAN'),
('5103', '51', 'KABUPATEN BADUNG'),
('5104', '51', 'KABUPATEN GIANYAR'),
('5105', '51', 'KABUPATEN KLUNGKUNG'),
('5106', '51', 'KABUPATEN BANGLI'),
('5107', '51', 'KABUPATEN KARANG ASEM'),
('5108', '51', 'KABUPATEN BULELENG'),
('5171', '51', 'KOTA DENPASAR'),
('5201', '52', 'KABUPATEN LOMBOK BARAT'),
('5202', '52', 'KABUPATEN LOMBOK TENGAH'),
('5203', '52', 'KABUPATEN LOMBOK TIMUR'),
('5204', '52', 'KABUPATEN SUMBAWA'),
('5205', '52', 'KABUPATEN DOMPU'),
('5206', '52', 'KABUPATEN BIMA'),
('5207', '52', 'KABUPATEN SUMBAWA BARAT'),
('5208', '52', 'KABUPATEN LOMBOK UTARA'),
('5271', '52', 'KOTA MATARAM'),
('5272', '52', 'KOTA BIMA'),
('5301', '53', 'KABUPATEN SUMBA BARAT'),
('5302', '53', 'KABUPATEN SUMBA TIMUR'),
('5303', '53', 'KABUPATEN KUPANG'),
('5304', '53', 'KABUPATEN TIMOR TENGAH SELATAN'),
('5305', '53', 'KABUPATEN TIMOR TENGAH UTARA'),
('5306', '53', 'KABUPATEN BELU'),
('5307', '53', 'KABUPATEN ALOR'),
('5308', '53', 'KABUPATEN LEMBATA'),
('5309', '53', 'KABUPATEN FLORES TIMUR'),
('5310', '53', 'KABUPATEN SIKKA'),
('5311', '53', 'KABUPATEN ENDE'),
('5312', '53', 'KABUPATEN NGADA'),
('5313', '53', 'KABUPATEN MANGGARAI'),
('5314', '53', 'KABUPATEN ROTE NDAO'),
('5315', '53', 'KABUPATEN MANGGARAI BARAT'),
('5316', '53', 'KABUPATEN SUMBA TENGAH'),
('5317', '53', 'KABUPATEN SUMBA BARAT DAYA'),
('5318', '53', 'KABUPATEN NAGEKEO'),
('5319', '53', 'KABUPATEN MANGGARAI TIMUR'),
('5320', '53', 'KABUPATEN SABU RAIJUA'),
('5321', '53', 'KABUPATEN MALAKA'),
('5371', '53', 'KOTA KUPANG'),
('6101', '61', 'KABUPATEN SAMBAS'),
('6102', '61', 'KABUPATEN BENGKAYANG'),
('6103', '61', 'KABUPATEN LANDAK'),
('6104', '61', 'KABUPATEN MEMPAWAH'),
('6105', '61', 'KABUPATEN SANGGAU'),
('6106', '61', 'KABUPATEN KETAPANG'),
('6107', '61', 'KABUPATEN SINTANG'),
('6108', '61', 'KABUPATEN KAPUAS HULU'),
('6109', '61', 'KABUPATEN SEKADAU'),
('6110', '61', 'KABUPATEN MELAWI'),
('6111', '61', 'KABUPATEN KAYONG UTARA'),
('6112', '61', 'KABUPATEN KUBU RAYA'),
('6171', '61', 'KOTA PONTIANAK'),
('6172', '61', 'KOTA SINGKAWANG'),
('6201', '62', 'KABUPATEN KOTAWARINGIN BARAT'),
('6202', '62', 'KABUPATEN KOTAWARINGIN TIMUR'),
('6203', '62', 'KABUPATEN KAPUAS'),
('6204', '62', 'KABUPATEN BARITO SELATAN'),
('6205', '62', 'KABUPATEN BARITO UTARA'),
('6206', '62', 'KABUPATEN SUKAMARA'),
('6207', '62', 'KABUPATEN LAMANDAU'),
('6208', '62', 'KABUPATEN SERUYAN'),
('6209', '62', 'KABUPATEN KATINGAN'),
('6210', '62', 'KABUPATEN PULANG PISAU'),
('6211', '62', 'KABUPATEN GUNUNG MAS'),
('6212', '62', 'KABUPATEN BARITO TIMUR'),
('6213', '62', 'KABUPATEN MURUNG RAYA'),
('6271', '62', 'KOTA PALANGKA RAYA'),
('6301', '63', 'KABUPATEN TANAH LAUT'),
('6302', '63', 'KABUPATEN KOTA BARU'),
('6303', '63', 'KABUPATEN BANJAR'),
('6304', '63', 'KABUPATEN BARITO KUALA'),
('6305', '63', 'KABUPATEN TAPIN'),
('6306', '63', 'KABUPATEN HULU SUNGAI SELATAN'),
('6307', '63', 'KABUPATEN HULU SUNGAI TENGAH'),
('6308', '63', 'KABUPATEN HULU SUNGAI UTARA'),
('6309', '63', 'KABUPATEN TABALONG'),
('6310', '63', 'KABUPATEN TANAH BUMBU'),
('6311', '63', 'KABUPATEN BALANGAN'),
('6371', '63', 'KOTA BANJARMASIN'),
('6372', '63', 'KOTA BANJAR BARU'),
('6401', '64', 'KABUPATEN PASER'),
('6402', '64', 'KABUPATEN KUTAI BARAT'),
('6403', '64', 'KABUPATEN KUTAI KARTANEGARA'),
('6404', '64', 'KABUPATEN KUTAI TIMUR'),
('6405', '64', 'KABUPATEN BERAU'),
('6409', '64', 'KABUPATEN PENAJAM PASER UTARA'),
('6411', '64', 'KABUPATEN MAHAKAM HULU'),
('6471', '64', 'KOTA BALIKPAPAN'),
('6472', '64', 'KOTA SAMARINDA'),
('6474', '64', 'KOTA BONTANG'),
('6501', '65', 'KABUPATEN MALINAU'),
('6502', '65', 'KABUPATEN BULUNGAN'),
('6503', '65', 'KABUPATEN TANA TIDUNG'),
('6504', '65', 'KABUPATEN NUNUKAN'),
('6571', '65', 'KOTA TARAKAN'),
('7101', '71', 'KABUPATEN BOLAANG MONGONDOW'),
('7102', '71', 'KABUPATEN MINAHASA'),
('7103', '71', 'KABUPATEN KEPULAUAN SANGIHE'),
('7104', '71', 'KABUPATEN KEPULAUAN TALAUD'),
('7105', '71', 'KABUPATEN MINAHASA SELATAN'),
('7106', '71', 'KABUPATEN MINAHASA UTARA'),
('7107', '71', 'KABUPATEN BOLAANG MONGONDOW UTARA'),
('7108', '71', 'KABUPATEN SIAU TAGULANDANG BIARO'),
('7109', '71', 'KABUPATEN MINAHASA TENGGARA'),
('7110', '71', 'KABUPATEN BOLAANG MONGONDOW SELATAN'),
('7111', '71', 'KABUPATEN BOLAANG MONGONDOW TIMUR'),
('7171', '71', 'KOTA MANADO'),
('7172', '71', 'KOTA BITUNG'),
('7173', '71', 'KOTA TOMOHON'),
('7174', '71', 'KOTA KOTAMOBAGU'),
('7201', '72', 'KABUPATEN BANGGAI KEPULAUAN'),
('7202', '72', 'KABUPATEN BANGGAI'),
('7203', '72', 'KABUPATEN MOROWALI'),
('7204', '72', 'KABUPATEN POSO'),
('7205', '72', 'KABUPATEN DONGGALA'),
('7206', '72', 'KABUPATEN TOLI-TOLI'),
('7207', '72', 'KABUPATEN BUOL'),
('7208', '72', 'KABUPATEN PARIGI MOUTONG'),
('7209', '72', 'KABUPATEN TOJO UNA-UNA'),
('7210', '72', 'KABUPATEN SIGI'),
('7211', '72', 'KABUPATEN BANGGAI LAUT'),
('7212', '72', 'KABUPATEN MOROWALI UTARA'),
('7271', '72', 'KOTA PALU'),
('7301', '73', 'KABUPATEN KEPULAUAN SELAYAR'),
('7302', '73', 'KABUPATEN BULUKUMBA'),
('7303', '73', 'KABUPATEN BANTAENG'),
('7304', '73', 'KABUPATEN JENEPONTO'),
('7305', '73', 'KABUPATEN TAKALAR'),
('7306', '73', 'KABUPATEN GOWA'),
('7307', '73', 'KABUPATEN SINJAI'),
('7308', '73', 'KABUPATEN MAROS'),
('7309', '73', 'KABUPATEN PANGKAJENE DAN KEPULAUAN'),
('7310', '73', 'KABUPATEN BARRU'),
('7311', '73', 'KABUPATEN BONE'),
('7312', '73', 'KABUPATEN SOPPENG'),
('7313', '73', 'KABUPATEN WAJO'),
('7314', '73', 'KABUPATEN SIDENRENG RAPPANG'),
('7315', '73', 'KABUPATEN PINRANG'),
('7316', '73', 'KABUPATEN ENREKANG'),
('7317', '73', 'KABUPATEN LUWU'),
('7318', '73', 'KABUPATEN TANA TORAJA'),
('7322', '73', 'KABUPATEN LUWU UTARA'),
('7325', '73', 'KABUPATEN LUWU TIMUR'),
('7326', '73', 'KABUPATEN TORAJA UTARA'),
('7371', '73', 'KOTA MAKASSAR'),
('7372', '73', 'KOTA PAREPARE'),
('7373', '73', 'KOTA PALOPO'),
('7401', '74', 'KABUPATEN BUTON'),
('7402', '74', 'KABUPATEN MUNA'),
('7403', '74', 'KABUPATEN KONAWE'),
('7404', '74', 'KABUPATEN KOLAKA'),
('7405', '74', 'KABUPATEN KONAWE SELATAN'),
('7406', '74', 'KABUPATEN BOMBANA'),
('7407', '74', 'KABUPATEN WAKATOBI'),
('7408', '74', 'KABUPATEN KOLAKA UTARA'),
('7409', '74', 'KABUPATEN BUTON UTARA'),
('7410', '74', 'KABUPATEN KONAWE UTARA'),
('7411', '74', 'KABUPATEN KOLAKA TIMUR'),
('7412', '74', 'KABUPATEN KONAWE KEPULAUAN'),
('7413', '74', 'KABUPATEN MUNA BARAT'),
('7414', '74', 'KABUPATEN BUTON TENGAH'),
('7415', '74', 'KABUPATEN BUTON SELATAN'),
('7471', '74', 'KOTA KENDARI'),
('7472', '74', 'KOTA BAUBAU'),
('7501', '75', 'KABUPATEN BOALEMO'),
('7502', '75', 'KABUPATEN GORONTALO'),
('7503', '75', 'KABUPATEN POHUWATO'),
('7504', '75', 'KABUPATEN BONE BOLANGO'),
('7505', '75', 'KABUPATEN GORONTALO UTARA'),
('7571', '75', 'KOTA GORONTALO'),
('7601', '76', 'KABUPATEN MAJENE'),
('7602', '76', 'KABUPATEN POLEWALI MANDAR'),
('7603', '76', 'KABUPATEN MAMASA'),
('7604', '76', 'KABUPATEN MAMUJU'),
('7605', '76', 'KABUPATEN MAMUJU UTARA'),
('7606', '76', 'KABUPATEN MAMUJU TENGAH'),
('8101', '81', 'KABUPATEN MALUKU TENGGARA BARAT'),
('8102', '81', 'KABUPATEN MALUKU TENGGARA'),
('8103', '81', 'KABUPATEN MALUKU TENGAH'),
('8104', '81', 'KABUPATEN BURU'),
('8105', '81', 'KABUPATEN KEPULAUAN ARU'),
('8106', '81', 'KABUPATEN SERAM BAGIAN BARAT'),
('8107', '81', 'KABUPATEN SERAM BAGIAN TIMUR'),
('8108', '81', 'KABUPATEN MALUKU BARAT DAYA'),
('8109', '81', 'KABUPATEN BURU SELATAN'),
('8171', '81', 'KOTA AMBON'),
('8172', '81', 'KOTA TUAL'),
('8201', '82', 'KABUPATEN HALMAHERA BARAT'),
('8202', '82', 'KABUPATEN HALMAHERA TENGAH'),
('8203', '82', 'KABUPATEN KEPULAUAN SULA'),
('8204', '82', 'KABUPATEN HALMAHERA SELATAN'),
('8205', '82', 'KABUPATEN HALMAHERA UTARA'),
('8206', '82', 'KABUPATEN HALMAHERA TIMUR'),
('8207', '82', 'KABUPATEN PULAU MOROTAI'),
('8208', '82', 'KABUPATEN PULAU TALIABU'),
('8271', '82', 'KOTA TERNATE'),
('8272', '82', 'KOTA TIDORE KEPULAUAN'),
('9101', '91', 'KABUPATEN FAKFAK'),
('9102', '91', 'KABUPATEN KAIMANA'),
('9103', '91', 'KABUPATEN TELUK WONDAMA'),
('9104', '91', 'KABUPATEN TELUK BINTUNI'),
('9105', '91', 'KABUPATEN MANOKWARI'),
('9106', '91', 'KABUPATEN SORONG SELATAN'),
('9107', '91', 'KABUPATEN SORONG'),
('9108', '91', 'KABUPATEN RAJA AMPAT'),
('9109', '91', 'KABUPATEN TAMBRAUW'),
('9110', '91', 'KABUPATEN MAYBRAT'),
('9111', '91', 'KABUPATEN MANOKWARI SELATAN'),
('9112', '91', 'KABUPATEN PEGUNUNGAN ARFAK'),
('9171', '91', 'KOTA SORONG'),
('9401', '94', 'KABUPATEN MERAUKE'),
('9402', '94', 'KABUPATEN JAYAWIJAYA'),
('9403', '94', 'KABUPATEN JAYAPURA'),
('9404', '94', 'KABUPATEN NABIRE'),
('9408', '94', 'KABUPATEN KEPULAUAN YAPEN'),
('9409', '94', 'KABUPATEN BIAK NUMFOR'),
('9410', '94', 'KABUPATEN PANIAI'),
('9411', '94', 'KABUPATEN PUNCAK JAYA'),
('9412', '94', 'KABUPATEN MIMIKA'),
('9413', '94', 'KABUPATEN BOVEN DIGOEL'),
('9414', '94', 'KABUPATEN MAPPI'),
('9415', '94', 'KABUPATEN ASMAT'),
('9416', '94', 'KABUPATEN YAHUKIMO'),
('9417', '94', 'KABUPATEN PEGUNUNGAN BINTANG'),
('9418', '94', 'KABUPATEN TOLIKARA'),
('9419', '94', 'KABUPATEN SARMI'),
('9420', '94', 'KABUPATEN KEEROM'),
('9426', '94', 'KABUPATEN WAROPEN'),
('9427', '94', 'KABUPATEN SUPIORI'),
('9428', '94', 'KABUPATEN MAMBERAMO RAYA'),
('9429', '94', 'KABUPATEN NDUGA'),
('9430', '94', 'KABUPATEN LANNY JAYA'),
('9431', '94', 'KABUPATEN MAMBERAMO TENGAH'),
('9432', '94', 'KABUPATEN YALIMO'),
('9433', '94', 'KABUPATEN PUNCAK'),
('9434', '94', 'KABUPATEN DOGIYAI'),
('9435', '94', 'KABUPATEN INTAN JAYA'),
('9436', '94', 'KABUPATEN DEIYAI'),
('9471', '94', 'KOTA JAYAPURA');

CREATE TABLE tb_roles(
	idRole char(50) PRIMARY KEY COMMENT 'ID wewenang (ex: role-(jnygis)-00001)',
	name char(150) NOT NULL COMMENT 'Nama wewenang',
	`desc` char(250) DEFAULT NULL COMMENT 'Deksripsi atau keterangan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Wewenang atau grup pengguna.';

INSERT INTO `tb_roles` VALUES ('role-0000000000-00001', 'Administrator', 'The highest authority that can view and access all data including the privileges of other users.', '2022-02-14 12:00:00', '2022-02-14 12:00:00');

CREATE TABLE tb_users(
	idUser char(50) PRIMARY KEY COMMENT 'ID pengguna (ex: user-(jnygis)-00001)',
	idRole char(50) NOT NULL COMMENT 'ID wewenang',
	img char(55) DEFAULT NULL COMMENT 'Foto profil',
	name char(150) NOT NULL COMMENT 'Nama pengguna',
	lang enum('english', 'bahasa') DEFAULT 'english' COMMENT 'Pilihan bahasa pada aplikasi',
	idNo char(30) DEFAULT NULL COMMENT 'Nomor induk karyawan',
	province char(5) NOT NULL COMMENT 'Kode Provinsi',
	city char(5) NOT NULL COMMENT 'Kode Kota atau Kabupaten',
	address char(250) NOT NULL COMMENT 'Alamat lengkap',
	phone char(30) NOT NULL COMMENT 'Nomor telepon',
	email char(150) NOT NULL COMMENT 'Alamat email',
	`password` char(100) NOT NULL COMMENT 'Kata sandi',
	status enum('granted', 'blocked') DEFAULT 'granted' COMMENT 'Status pengguna',
	`key` char(15) DEFAULT NULL COMMENT 'Kode akses sementara',
	fgtToken char(100) DEFAULT NULL COMMENT 'Token untuk ubah kata sandi',
	fgtDate datetime DEFAULT NULL COMMENT 'Waktu terakhir ubah kata sandi',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Pengguna.';

INSERT INTO `tb_users` VALUES ('user-0000000000-00001', 'role-0000000000-00001', 'user-0000000000-00001.png', 'Binsar Harseno', 'english', 'ESBI/DEV/2022/0002', '32', '3201', 'Perumahan Puri Artha Sentosa, Blok D No. 21 RT/RW 002/011, Kel. Waringin Jaya, Kec. Bojonggede', '087871894990', 'admin@esbifarma.co.id', '3920ec5cc77e4137c1b3ecf795d13b30e3b4ff1d416fce8344c01b43fd2376cd', 'granted', 'ebaa741e2d', NULL, '2022-02-14 12:00:00', '2022-02-14 12:00:00', '2022-02-14 12:00:00');

CREATE TABLE tb_notifications(
	idNotif bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID notifikasi (auto increment)',
	idUser char(50) NOT NULL COMMENT 'ID pengguna (asal notifikasi dibuat)',
	toIdUser char(50) NOT NULL COMMENT 'ID pengguna (tujuan notifikasi dibuat)',
	title char(150) NOT NULL COMMENT 'Judul notifikasi',
	`desc` char(250) NOT NULL COMMENT 'Deskripsi atau keterangan singkat',
	href char(150) DEFAULT NULL COMMENT 'Tautan pada tombol (optional)',
	status enum('y', 'n') DEFAULT 'n' COMMENT 'Status notifikasi sudah dilihat atau belum',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_notifications_users` FOREIGN KEY (`idUser`) REFERENCES `tb_users` (`idUser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Notifikasi pengguna.';

CREATE TABLE tb_logs(
	idLog bigint UNSIGNED NOT NULL COMMENT 'ID catatan (auto increment)',
	idUser char(50)	NOT NULL COMMENT 'ID pengguna',
	ip char(30) NOT NULL COMMENT 'Alamat IP pengguna',
	target char(150) NOT NULL COMMENT 'ID unik atau nama data',
	`desc` char(250) NOT NULL COMMENT 'Deskripsi atau keterangan',
	`old` text DEFAULT NULL COMMENT 'Data sebelumnya',
	`created` datetime NOT NULL COMMENT 'Waktu data dibuat',
	CONSTRAINT `FK_logs_users` FOREIGN KEY (`idUser`) REFERENCES `tb_users` (`idUser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Catatan aktivitas pengguna.';

CREATE TABLE tb_menus(
	idMenu char(50) PRIMARY KEY COMMENT 'ID halaman (ex: menu-00001)',
	`order` TINYINT(3) NOT NULL COMMENT 'Urutan sebagai posisi halaman di menu',
	name char(150) NOT NULL COMMENT 'Nama halaman',
	url char(150) DEFAULT NULL COMMENT 'Tautan halaman',
	title char(150) NOT NULL COMMENT 'Judul halaman',
	icon char(50) DEFAULT NULL COMMENT 'Nama ikon (berdasarkan Google Material Icons)',
	`type` enum('parent', 'child') DEFAULT 'parent' COMMENT 'Tipe halaman',
	child_of char(150) DEFAULT NULL COMMENT 'Anak dari ? (nama halaman)',
	searchbar enum('y', 'n') DEFAULT 'y' COMMENT 'Opsi untuk pencarian di searchbar',
	sidebar enum('y', 'n') DEFAULT 'y' COMMENT 'Opsi untuk tampil dibagian menu',
	control enum('y', 'n') DEFAULT 'y' COMMENT 'Opsi untuk dapat dibatasi oleh administator',
	visibility enum('private', 'protected') DEFAULT 'private' COMMENT 'Visilibitas (Developer Mode)',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Halaman - halaman dalam Cnryflex.';

INSERT INTO `tb_menus` VALUES
('menu-00001', 1, 'pdashboard', NULL, 'Overview', 'poll', 'parent', NULL, 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00002', 2, 'p_overview', 'pages/overview', 'Overview', NULL, 'child', 'pdashboard', 'n', 'y', 'n', 'private', NOW(), NOW()),
('menu-00003', 3, 'p_pageview', 'pages/pageview.list', 'Pageviews', NULL, 'child', 'pdashboard', 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00004', 4, 'puser', NULL, 'User Management', 'group', 'parent', NULL, 'n', 'y', 'n', 'private', NOW(), NOW()),
('menu-00005', 5, 'p_user', 'pages/user.list', 'Users', NULL, 'child', 'puser', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00006', 6, 'p_role', 'pages/role.list', 'Roles', NULL, 'child', 'puser', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00007', 7, 'p_log', 'pages/log.list', 'Activity Logs', NULL, 'child', 'puser', 'y', 'y', 'y', 'private', NOW(), NOW()),

('menu-00008', 8, 'pproduct', NULL, 'Products', 'spa', 'parent', NULL, 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00009', 9, 'p_product', 'pages/product.list', 'All Products', NULL, 'child', 'pproduct', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00010', 10, 'p_category', 'pages/category.list', 'Categories', NULL, 'child', 'pproduct', 'y', 'y', 'y', 'private', NOW(), NOW()),

('menu-00011', 11, 'pcustomer', NULL, 'Customers', 'supervised_user_circle', 'parent', NULL, 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00012', 12, 'p_customer', 'pages/customer.list', 'All Customers', NULL, 'child', 'pcustomer', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00013', 13, 'p_commission', 'pages/commission.list', 'Commissions', NULL, 'child', 'pcustomer', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00014', 14, 'p_reward', 'pages/reward.list', 'Rewards', NULL, 'child', 'pcustomer', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00015', 15, 'p_punishment', 'pages/punishment.list', 'Punishments', NULL, 'child', 'pcustomer', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00016', 16, 'p_information', 'pages/information.list', 'Information', NULL, 'child', 'pcustomer', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00017', 17, 'p_tool', 'pages/tool.list', 'Marketing Tools', NULL, 'child', 'pcustomer', 'y', 'y', 'y', 'private', NOW(), NOW()),

('menu-00018', 18, 'porder', NULL, 'Transactions', 'receipt_long', 'parent', NULL, 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00019', 19, 'p_order', 'pages/order.list', 'Orders', NULL, 'child', 'porder', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00020', 20, 'p_voucher', 'pages/voucher.list', 'Vouchers', NULL, 'child', 'porder', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00021', 21, 'p_report', NULL, 'Report', NULL, 'child', 'porder', 'y', 'y', 'y', 'private', NOW(), NOW()),

('menu-00022', 22, 'ppages', NULL, 'Pages', 'web', 'parent', NULL, 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00023', 23, 'pmainpage', NULL, 'Main Pages', NULL, 'child', 'ppages', 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00024', 24, 'psubpage', NULL, 'Sub Pages', NULL, 'child', 'ppages', 'y', 'y', 'y', 'private', NOW(), NOW()),

('menu-00099', 99, 'message', 'pages/message.list', 'Messages', 'question_answer', 'parent', NULL, 'y', 'y', 'y', 'private', NOW(), NOW()),
('menu-00100', 100, 'setting', 'pages/setting.edit', 'Settings', 'public', 'parent', NULL, 'n', 'y', 'y', 'private', NOW(), NOW()),
('menu-00101', 101, 'profile', 'pages/profile.view', 'My Profile', 'face', 'parent', NULL, 'n', 'y', 'n', 'private', NOW(), NOW()),
('menu-00102', 102, 'notification', 'pages/notification.list', 'Notifications', 'upcoming', 'parent', NULL, 'y', 'n', 'n', 'private', NOW(), NOW()),
('menu-00103', 103, 'pdeveloper', NULL, 'Developer Mode', 'developer_board', 'parent', NULL, 'n', 'y', 'n', 'protected', NOW(), NOW()),
('menu-00104', 104, 'p_error', 'pages/error.list', 'Errors', NULL, 'child', 'pdeveloper', 'n', 'y', 'n', 'protected', NOW(), NOW()),
('menu-00105', 105, 'p_advancedSetting', 'pages/advanceSetting.edit', 'Advanced Settings', NULL, 'child', 'pdeveloper', 'n', 'y', 'n', 'protected', NOW(), NOW());

CREATE TABLE tb_privileges(
	idPrivil bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY comment 'ID hak akses (auto increment)',
	idUser char(50) NOT NULL COMMENT 'ID pengguna',
	namePage char(150) NOT NULL COMMENT 'Nama halaman',
	`type` enum('all', 'edit', 'read') DEFAULT 'read' COMMENT 'Kemampuan eksekusi',
	created datetime NOT NULL COMMENT 'Waktu data dibuat'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Hak akses dan eksekusi pengguna.';

INSERT INTO tb_privileges(`idUser`, `namePage`, `type`, `created`) VALUES
('user-0000000000-00001', 'pdashboard', 'all', NOW()),
('user-0000000000-00001', 'p_overview', 'all', NOW()),
('user-0000000000-00001', 'p_pageview', 'all', NOW()),
('user-0000000000-00001', 'puser', 'all', NOW()),
('user-0000000000-00001', 'p_user', 'all', NOW()),
('user-0000000000-00001', 'p_role', 'all', NOW()),
('user-0000000000-00001', 'p_log', 'all', NOW()),
('user-0000000000-00001', 'pproduct', 'all', NOW()),
('user-0000000000-00001', 'p_product', 'all', NOW()),
('user-0000000000-00001', 'p_category', 'all', NOW()),
('user-0000000000-00001', 'pcustomer', 'all', NOW()),
('user-0000000000-00001', 'p_customer', 'all', NOW()),
('user-0000000000-00001', 'p_commission', 'all', NOW()),
('user-0000000000-00001', 'p_reward', 'all', NOW()),
('user-0000000000-00001', 'p_punishment', 'all', NOW()),
('user-0000000000-00001', 'p_information', 'all', NOW()),
('user-0000000000-00001', 'p_tool', 'all', NOW()),
('user-0000000000-00001', 'porder', 'all', NOW()),
('user-0000000000-00001', 'p_order', 'all', NOW()),
('user-0000000000-00001', 'p_voucher', 'all', NOW()),
('user-0000000000-00001', 'p_report', 'all', NOW()),
('user-0000000000-00001', 'ppages', 'all', NOW()),
('user-0000000000-00001', 'pmainpage', 'all', NOW()),
('user-0000000000-00001', 'psubpage', 'all', NOW()),
('user-0000000000-00001', 'message', 'all', NOW()),
('user-0000000000-00001', 'setting', 'all', NOW()),
('user-0000000000-00001', 'profile', 'all', NOW()),
('user-0000000000-00001', 'notification', 'all', NOW()),
('user-0000000000-00001', 'pdeveloper', 'all', NOW()),
('user-0000000000-00001', 'p_error', 'all', NOW()),
('user-0000000000-00001', 'p_advancedSetting', 'all', NOW());

CREATE TABLE tb_pageviews(
	idView bigint unsigned auto_increment PRIMARY KEY COMMENT 'ID kunjungan (auto increment)',
	LOCATION char(150) NOT NULL COMMENT 'ID halaman atau ID produk',
	url char(150) NOT NULL COMMENT 'URL halaman',
	referrer char(100) DEFAULT NULL COMMENT 'URL sebelumnya (ex: backlinks atau hasil pencarian)',
	bowser char(100) NOT NULL COMMENT 'Web browser yang digunakan',
	os char(100) NOT NULL COMMENT 'Sistem operasi yang digunakan',
	device char(100) NOT NULL COMMENT 'Jenis perangkat yang digunakan',
	ip char(30) NOT NULL COMMENT 'Alamat IP',
	country char(100) NOT NULL COMMENT 'Nama negara',
	city char(100) NOT NULL COMMENT 'Nama kota atau kabupaten',
	longitude char(50) NOT NULL COMMENT 'Titik koordinat (longitude)',
	latitude char(50) NOT NULL COMMENT 'Titik koordinate (latitude)',
	visited datetime NOT NULL COMMENT 'Waktu kunjungan'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Data pengunjung tiap halaman situs web.';

CREATE TABLE tb_settings(
	idSet tinyint(3) unsigned PRIMARY KEY COMMENT 'ID pengaturan (tunggal)',
	img char(55) NOT NULL COMMENT 'Logo utama situs web',
	tagline char(150) NOT NULL COMMENT 'Judul utama situs web',
	company char(150) NOT NULL COMMENT 'Nama perusahaan atau instansi',
	trademark char(60) NOT NULL COMMENT 'Singkatan atau merek dagang',
	maintenance enum('y', 'n') DEFAULT 'n' COMMENT 'Status pemeliharan',
	address char(250) NOT NULL COMMENT 'Alamat lengkap',
	email char(150) NOT NULL COMMENT 'Alamat email',
	phone char(100) NOT NULL COMMENT 'Nomor telepon',
	whatsapp char(150) NOT NULL COMMENT 'Tautan Whatsapp',
	facebook char(150) DEFAULT NULL COMMENT 'Tautan Facebook',
	instagram char(150) DEFAULT NULL COMMENT 'Tautan Instagram',
	linkedin char(150) DEFAULT NULL COMMENT 'Tautan LinkedIn',
	latitude char(50) NOT NULL COMMENT 'Koordinat latitude',
	longitude char(50) NOT NULL COMMENT 'Koordinat longitude',
	googleMaps char(250) NOT NULL COMMENT 'Tautan Google Maps',
	officeHours char(150) DEFAULT NULL COMMENT 'Jadwal & waktu kantor',
	`desc` text DEFAULT NULL COMMENT 'Deskripsi atau keterangan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Pengaturan standar.';

INSERT INTO `tb_settings` VALUES
(1, 'logo.png', 'One Stop Healthy Solution', 'PT. Esbi Batara Niaga Indonesia', 'Esbi Farma', 'n', 'Gedung 18 Office Park Lt.25 Suite A2 Jl.TB Simatupang No.18 Jakarta - 12430', 'cs@esbifarma.co.id', '081219807624', 'https://api.whatsapp.com/send?phone=+6281219807624', 'https://www.facebook.com/esbi.id/', 'https://www.instagram.com/esbi.farma/', 'https://www.linkedin.com/company/esbiindonesia', '106.8298112', '-6.2992983', 'https://www.google.com/maps/place/18+Office+Park/@-6.2992983,106.8298112,17z/data=!3m1!4b1!4m5!3m4!1s0x2e69edf7d12a98d3:0xa29985100f9b696e!8m2!3d-6.2993036!4d106.8319999', 'Senin - Sabtu
08.00 – 16.00 WIB (Hari Kerja)', 'Produk herbal yang kami hadirkan terbuat dari 100% bahan ekstrak alami terstandar. Diformulasikan menjadi senyawa aktif dalam bentuk kapsul, yang mamou bekerja efektif dan sistematis.', NOW(), NOW());

CREATE TABLE tb_advancedSettings (
	idAdSet tinyint(3) NOT NULL COMMENT 'ID pengaturan lanjutan (tunggal)',
	HOST char(150) NOT NULL COMMENT 'Host atau domain',
	SMTPAuth TINYINT(1) DEFAULT '1' COMMENT 'SMTP Authentication',
	SMTPSecure char(50) NOT NULL COMMENT 'SSL',
	username char(150) NOT NULL COMMENT 'Alamat email',
	`password` char(150) NOT NULL COMMENT 'Kata sandi email',
	port int(11) NOT NULL COMMENT 'TCP Port',
	sender char(150) NOT NULL COMMENT 'Nama pengirim',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] pengaturan lanjutan (Developer Mode).';

CREATE TABLE tb_errors(
	idErr bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID pesan kesalahan (auto increment)',
	`type` enum('warning', 'error') DEFAULT 'error' COMMENT 'Status pesan',
	message text NOT NULL COMMENT 'Isi pesan',
	LOCATION varchar(300) DEFAULT NULL COMMENT 'Lokasi sumber pesan',
	`user` json NOT NULL COMMENT 'Informasi data - data pengguna (JSON)',
	status enum ('y', 'n') DEFAULT 'n' COMMENT '''y'' Jika pesan kesalahan sudah diatasi',
	`desc` text DEFAULT NULL COMMENT 'Deskripsi atau keterangan tambahan',
	created datetime NOT NULL COMMENT 'Waktu data diubah',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[CX] Pesan kesalahan.';

CREATE TABLE tb_messages(
	idMess bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID pesan (auto increment)',
	name char(150) NOT NULL COMMENT 'Nama pengirim',
	email char(150) NOT NULL COMMENT 'Alamat email',
	phone char(30) NOT NULL COMMENT 'Nomor telepon',
	content varchar(600) NOT NULL COMMENT 'Waktu data dibuat',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Pesan masuk dari halaman: Hubungi Kami.';

CREATE TABLE tb_levels(
	idLevel char(50) PRIMARY KEY COMMENT 'ID tier atau tingkatan mitra (ex: level-(jnygis)-00001)',
	name char(150) NOT NULL COMMENT 'Nama tingkatan',
	minqty int unsigned NOT NULL COMMENT 'Jumlah kuantitas yang harus dibeli untuk lolos sebagai mitra',
	discount tinyint DEFAULT NULL COMMENT 'Jumlah diskon yang di dapat setelah lolos sebagai mitra',
	freeShipping int UNSIGNED DEFAULT NULL COMMENT 'Minimum kuantitas untuk mendapatkan gratis biaya pengiriman',
	period tinyint UNSIGNED DEFAULT NULL COMMENT 'Periode hadiah / hukuman dalam bentuk bulan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Tier atau tingkatan kemitraan pelanggan.';

CREATE TABLE tb_customers(
	idCust char(50) PRIMARY KEY COMMENT 'ID pelanggan (ex: cust-(jnygis)-00001)',
	idLevel char(50) NOT NULL COMMENT 'Tingkatan sebagai mitra',
	img char(55) DEFAULT NULL COMMENT 'Foto profil',
	name char(150) NOT NULL COMMENT 'Nama lengkap',
	gender enum('wanita', 'pria') NOT NULL COMMENT 'Jenis kelamin',
	birthday date NOT NULL COMMENT 'Tanggal lahir',
	phone char(30) NOT NULL COMMENT 'Nomor telepon',
	email char(150) NOT NULL COMMENT 'Alamat email',
	`password` char(100) NOT NULL COMMENT 'Kata sandi',
	fgtToken char(100) NOT NULL COMMENT 'Kode sementara untuk verifikasi lupa kata sandi',
	fgtDate datetime DEFAULT NULL COMMENT 'Waktu pengajuan lupa kata sandi',
	status enum('y', 'n') DEFAULT 'y' COMMENT 'Status pelanggan (aktif atau tidak)',
	referral char(20) NOT NULL COMMENT 'Kode referral (ex: binsar6377)',
	byReferral char(20) DEFAULT NULL COMMENT 'Kode referral yang digunakan saat registrasi',
	comissions bigint unsigned DEFAULT NULL COMMENT 'Jumlah komisi yang dimiliki',
	poins bigint unsigned DEFAULT NULL COMMENT 'Jumlah poin yang dimiliki',
	minqty enum('y', 'n') DEFAULT 'n' COMMENT 'Status syarat program kemitraan (minimum quantity dalam sekali pembelian)',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_customers_levels` FOREIGN KEY (`idLevel`) REFERENCES `tb_levels` (`idLevel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Data pelanggan biasa atau yang telah bergabung menjadi mitra.';

CREATE TABLE tb_address(
	idAddress char(50) PRIMARY KEY COMMENT 'ID alamat (ex: address-(jnygis)-00001)',
	idCust char(50) NOT NULL COMMENT 'ID pelanggan',
	title char(150) NOT NULL COMMENT 'Judul alamat',
	recipient char(150) NOT NULL COMMENT 'Nama penerima',
	phone char(30) NOT NULL COMMENT 'Nomor telepon penerima',
	address char(250) NOT NULL COMMENT 'Alamat lengkap',
	province char(5) NOT NULL COMMENT 'Kode Provinsi',
	city char(5) NOT NULL COMMENT 'Kode Kota / Kabupaten',
	district char(5) NOT NULL COMMENT 'Kode Kelurahan',
	zip char(5) NOT NULL COMMENT 'Kode Pos',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_address_customers` FOREIGN KEY (`idCust`) REFERENCES `tb_customers` (`idCust`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Alamat - alamat yang disimpan pelanggan.';

CREATE TABLE tb_customer_notifications(
	idNotif  bigint unsigned auto_increment PRIMARY KEY comment 'ID notifikasi pelanggan (auto increment)',
	idCust char(50) NOT NULL COMMENT 'ID pelanggan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_customer_notifications_customers` FOREIGN KEY (`idCust`) REFERENCES `tb_customers` (`idCust`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Notifikasi yang diterima pelanggan.';

CREATE TABLE tb_customer_stocks(
	idStock char(50) PRIMARY KEY COMMENT 'ID stok mitra (ex: stock-(jnygis)-00001)',
	idCust char(50) NOT NULL COMMENT 'ID pelanggan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_customer_stocks_customers` FOREIGN KEY (`idCust`) REFERENCES `tb_customers` (`idCust`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Stok yang dimiliki oleh mitra tertentu.';

CREATE TABLE tb_tools(
	idTool char(50) PRIMARY KEY COMMENT 'ID alat pemasaran (marketing tools) (ex: tool-(jnygis)-00001)',
	title char(150) NOT NULL COMMENT 'Nama alat',
	`desc` varchar(600) DEFAULT NULL COMMENT 'Deskripsi atau keterangan',
	visibility enum('y', 'n') DEFAULT 'y' COMMENT 'Visibilitas',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Alat pemasaran (marketing tools) untuk mitra.';

CREATE TABLE tb_tool_items(
	idToolItem char(50) PRIMARY KEY COMMENT 'ID per item alat pemasaran (marketing tools) (ex: toolItem-(jnygis)-00001)',
	idTool char(50) NOT NULL COMMENT 'ID alat',
	name char(150) NOT NULL COMMENT 'Nama alat',
	file char(55) NOT NULL COMMENT 'Berkas yang dapat diunduh pelanggan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_tool_items_tools` FOREIGN KEY (`idTool`) REFERENCES `tb_tools` (`idTool`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Daftar alat pemasaran untuk mitra.';

CREATE TABLE tb_commissions(
	idComm char(50) PRIMARY KEY COMMENT 'ID komisi pelanggan (ex: comm-(jnygis)-00001)',
	idCust char(50) NOT NULL COMMENT 'ID pelanggan',
	fromIdCust char(50) DEFAULT NULL COMMENT 'Jika komisi dari registrasi pelanggan lain (referral)',
	amount bigint unsigned COMMENT 'Jumlah komisi yang diterima',
	status enum('pending', 'success', 'rejected') DEFAULT 'pending' COMMENT 'Status komisi',
	`desc` char(250) DEFAULT NULL COMMENT 'Deskripsi atau keterangan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_commissions_customers` FOREIGN KEY (`idCust`) REFERENCES `tb_customers` (`idCust`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Data komisi tiap pelanggan atau mitra.';

CREATE TABLE tb_categories(
	idCat char(50) PRIMARY KEY COMMENT 'ID kategori (ex: cat-(jnygis)-00001)',
	name char(150) NOT NULL COMMENT 'Nama kategori',
	`desc` char(250) DEFAULT NULL COMMENT 'Deskripsi atau keterangan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Kategori produk.';

CREATE TABLE tb_products(
	idPro char(50) PRIMARY KEY COMMENT 'ID produk (ex: pro-(jnygis)-00001)',
	idCat char(50) NOT NULL COMMENT 'ID kategori',
	name char(150) NOT NULL COMMENT 'Nama produk',
	utility varchar(300) NOT NULL COMMENT 'Khasiat atau kegunaan',
	weight int unsigned NOT NULL COMMENT 'Berat produk (gram)',
	stock int unsigned NOT NULL COMMENT 'Stok produk',
	price bigint unsigned NOT NULL COMMENT 'Harga produk',
	discount tinyint unsigned DEFAULT NULL COMMENT 'Diskon produk',
	discountAvailable enum('all', 'basic', 'partnership') DEFAULT 'all' COMMENT 'Target diskon',
	discountEnd date DEFAULT NULL COMMENT 'Tanggal diskon berakhir',
	`desc` char(250) DEFAULT NULL COMMENT 'Deskripsi atau keterangan',
	visibility enum('y', 'n') DEFAULT 'y' COMMENT 'Visibilitas',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_products_categories` FOREIGN KEY (`idCat`) REFERENCES `tb_categories` (`idCat`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Produk.';

CREATE TABLE tb_product_imgs(
	idProImg char(50) PRIMARY KEY COMMENT 'ID gambar produk (ex: proImg-(jnygis)-00001)',
	idPro char(50) NOT NULL COMMENT 'ID produk',
	file char(55) NOT NULL COMMENT 'Gambar atau video',
	visibility enum('y', 'n') DEFAULT 'y' COMMENT 'Visibilitas',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data dibuat',
	CONSTRAINT `FK_product_imgs_products` FOREIGN KEY (`idPro`) REFERENCES `tb_products` (`idPro`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Gambar - gambar produk.';

CREATE TABLE tb_promos(
	idPromo char(50) primary key comment 'ID promo (ex: promo-(jnygis)-00001)',
	file char(55) not null comment 'Berkas gambar atau video',
	name char(150) not null comment 'Nama promo',
	content varchar(600) not null comment 'Keterangan promo',
	`dateStart` datetime not null comment 'Waktu promo dimulai',
	`dateEnd` datetime not null comment 'Waktu promo berakhir',
	status enum('y', 'n') default 'n' comment 'Visibilitas',
	created datetime not null comment 'Waktu data dibuat',
	modified timestamp default current_timestamp on update current_timestamp comment 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Promo yang dapat digunakan pelanggan.';

CREATE TABLE tb_vouchers(
	idVoucher char(50) PRIMARY KEY COMMENT 'ID kupon (ex: voucher-(jnygis)-00001)',
	name char(150) NOT NULL COMMENT 'Nama kupon',
	code char(150) NOT NULL COMMENT 'Kode kupon untuk digunakan',
	`type` enum('price', 'shipping') DEFAULT 'price' COMMENT 'Price: kupon untuk potongan harga. Shipping : kupon gratis ongkos kirim',
	amount bigint unsigned NOT NULL COMMENT 'Nilai kupon',
	maxCust tinyint unsigned NOT NULL COMMENT 'Jumlah maksimal pelanggan yang menggunakan kupon',
	startDate date NOT NULL COMMENT 'Waktu kupon dimulai',
	`endDate` date NOT NULL COMMENT 'Waktu kupon berakhir',
	`desc` varchar(600) DEFAULT NULL COMMENT 'Deskripsi atau keterangan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Voucher atau kupon.';

CREATE TABLE tb_pays(
	idPay char(50) PRIMARY KEY COMMENT 'ID bayar (ex: pay-(jnygis)-00001)',
	img char(55) DEFAULT NULL COMMENT 'Bukti pembayaran atau transfer',
	`method` char(50) NOT NULL COMMENT 'Metode pembayaran',
	`response` json DEFAULT NULL COMMENT 'Response API payment gateway',
	status enum('pending', 'success', 'failed') DEFAULT 'pending' COMMENT 'Status pembayaran',
	expiredDate datetime NOT NULL COMMENT 'Batas akhir pembayaran',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Status pembayaran pesanan pelanggan.';

CREATE TABLE tb_orders(
	idOrder char(50) PRIMARY KEY COMMENT 'ID pesanan (ex: order-(jnygis)-00001)',
	idCust char(50) NOT NULL COMMENT 'ID pelanggan',
	idPay char(50) NOT NULL COMMENT 'ID bayar',
	idVoucher char(50) DEFAULT NULL COMMENT 'ID kupon',
	recipient char(150) NOT NULL COMMENT 'Nama penerima',
	phone char(30) NOT NULL COMMENT 'Nomor telepon',
	address char(250) NOT NULL COMMENT 'Alamat pengiriman',
	province char(5) NOT NULL COMMENT 'Kode Provinsi',
	city char(5) NOT NULL COMMENT 'Kode Kota / Kabupaten',
	district char(5) NOT NULL COMMENT 'Kode Kelurahan',
	zip char(5) NOT NULL COMMENT 'Kode Pos',
	courier char(150) NOT NULL COMMENT 'Jasa pengiriman',
	service char(150) NOT NULL COMMENT 'Paket pengiriman',
	weight int unsigned NOT NULL COMMENT 'Total berat seluruh produk (Gram)',
	shipping bigint unsigned NOT NULL COMMENT 'Biaya pengiriman',
	subtotal bigint unsigned NOT NULL COMMENT 'Total pembelian',
	total bigint unsigned NOT NULL COMMENT 'Total yang harus dibayar',
	trackingNumber bigint unsigned NOT NULL COMMENT 'Nomor resi atau nomor waybill',
	deliveryDate date NOT NULL COMMENT 'Waktu pengiriman',
	steps enum('payment', 'prepare', 'delivery', 'done', 'cancel') DEFAULT 'payment' COMMENT 'Posisi pesanan',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_orders_customers` FOREIGN KEY (`idCust`) REFERENCES `tb_customers` (`idCust`),
	CONSTRAINT `FK_orders_pays` FOREIGN KEY (`idPay`) REFERENCES `tb_pays` (`idPay`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Pesanan atau transaksi pelanggan.';

CREATE TABLE tb_order_items(
	idOrderItem char(50) primary key comment 'ID produk dalam pesanan (idOrderItem-(jnygis)-00001)',
	idOrder char(50) DEFAULT NULL COMMENT 'ID pesanan, kosong jika proses hanya sampai keranjang',
	idPro char(50) not null comment 'ID produk',
	qty tinyint unsigned not null comment 'Kuantitas',
	price bigint unsigned not null comment 'Harga produk',
	weight int unsigned not null comment 'Berat produk',
	created datetime not null comment 'Waktu data dibuat',
	modified timestamp default current_timestamp on update current_timestamp comment 'Waktu data diubah',
	constraint `FK_order_items_orders` foreign key (`idOrder`) references `tb_orders` (`idOrder`),
	constraint `FK_order_items_products` foreign key (`idPro`) references `tb_products` (`idPro`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Daftar produk dalam pesanan pelanggan.';

CREATE TABLE tb_wishlist(
	idWish char(50) PRIMARY KEY COMMENT 'ID daftar keinginan',
	idCust char(50) NOT NULL COMMENT 'ID pelanggan',
	idPro char(50) NOT NULL COMMENT 'ID produk',
	qty tinyint unsigned NOT NULL COMMENT 'Kuantitas',
	created datetime NOT NULL COMMENT 'Waktu data dibuat',
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Waktu data diubah',
	CONSTRAINT `FK_wishlist_customers` FOREIGN KEY (`idCust`) REFERENCES `tb_customers` (`idCust`),
	CONSTRAINT `FK_wishlist_products` FOREIGN KEY (`idPro`) REFERENCES `tb_products` (`idPro`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Daftar produk keinginan pelanggan.';

CREATE TABLE tb_testimonials(
	idTes char(50) primary key comment 'ID testimonial (ex: tes-(jnygis)-00001)',
	idOrder char(50) not null comment 'ID pesanan',
	idPro char(50) not null comment 'ID produk',
	star tinyint unsigned not null comment 'Rating bintang',
	content varchar(600) default null comment 'Isi testimonial',
	visiblity enum('y', 'n') default 'n' comment 'Visiblitas',
	created datetime not null comment 'Waktu data dibuat',
	modified timestamp default current_timestamp on update current_timestamp comment 'Waktu data diubah',
	constraint `FK_testimonials_orders` foreign key (`idOrder`) references `tb_orders` (`idOrder`),
	constraint `FK_testimonials_products` foreign key (`idPro`) references `tb_products` (`idPro`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='[FRONT] Testimonial pelanggan setelah proses transaksi selesai.';
